module.exports = {
  printWidth: 70,
  useTabs: false,
  semi: false,
  singleQuote: true,
  quoteProps: "preserve",
  jsxSingleQuote: false,
  trailingComma: "all",
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: "avoid",
  requirePragma: false,
  vueIndentScriptAndStyle: true,
  endOfLine: "auto",
}
